### ISSUE TITLE
findBarcodeSerie NL

### ISSUE THREAD

**Issue by nletech** [firstred/postnl-api-php#11]
Hello 

In postnl.php file line 681

`
        $serie = $this->findBarcodeSerie(
            $type,
            $range,
            strtoupper($iso) !== 'NL' && in_array(strtoupper($iso), static::$threeSCountries)
        );
`

i don't understand why code like this?
how to setting args, if i just want to use barcode serie to 0000000-9999999 

many thanks

**Comment by nletech** [comment]
`
{
    "Fault": [
        {
            "Shipment": "3SDMSU987022441",
            "Errors": [
                {
                    "Code": "14004",
                    "Omschrijving": "Barcode length must be 13 characters"
                },
                {
                    "Code": "10701",
                    "Omschrijving": "Barcode is niet valide voor Proces"
                }
            ]
        }
    ]
}
`

i shipment from NL to CN

**Comment by firstred** [comment]
Sorry, I am not able to help you here. PostNL doesn't provide us with enough support and documentation to be able to code for these cases. I believe shipments to China indeed require a 3S code, but the whole procedure is kind of a black box to me right now.

**Comment by firstred** [comment]
When in doubt, you can use the shipping web service that is going to be added to v1.2.0.
