### ISSUE TITLE
DeliveryOptions encoding breaks comma separation in LocationService

### ISSUE THREAD

**Issue by cavias** [firstred/postnl-api-php#13]
I've noticed that if you add options to the DeliveryOptions, such as `PGE`, it will try to form a comma separated option such as `PG,PGE`.

However, when encoded for the URL it will also encode that comma to its hex value, resulting in `DeliveryOptions=PG%2CPGE`, which doesn't work. 

I only tested for LocationService REST.

**Comment by firstred** [comment]
Interesting. One would expect that regular URL encoding would not be a problem, but maybe something's checking/rejecting the URL on their end.
I will definitely look into this before the next release!

**Comment by xdizzy12** [comment]
To add: The URL is accepted on their end, but there is no way to filter specific DeliveryOptions. In my case, I want PGE locations only, but it returns all locations with or without PGE. It might be that they only sanity check if DeliveryOptions exists, not if its valid. 

Manually replacing the encoded DeliveryOptions value from `PGE%C2PGE` to `PG,PGE` actually does return the properly filtered values. So at least it does seem fixable.

**Comment by xdizzy12** [comment]
For our own website I have made a fix by extending LocationService and overwriting `buildGetNearestLocationsRequestREST()` and `buildGetLocationsInAreaRequestREST()`. 

Removed the `query['DeliveryOptions']` default `PG` value (it seems it filters by 'OR' logic, not 'AND') and adding `PHP_QUERY_RFC1738` encoding to the Guzzle build_query() method. 

Seems to work fine for me.

**Comment by firstred** [comment]
Thanks for the suggestion! I will make sure it becomes part of version 1.2.0.

The encoding indeed was incorrect and now that I've had a look at what I have in production, it seems that I have already applied this patch, but it has never become part of the library. Sorry about that!

**Comment by firstred** [comment]
I made the following changes in 1.2.0 to address this issue:

- Remove support for PGE, since PostNL no longer offers these kinds of shipments
- Using PHP's built-in `http_build_query` function, it defaults to `PHP_QUERY_RFC1738`
