### ISSUE TITLE
Getting the PDF label without saving it

### ISSUE THREAD

**Issue by GetMagented** [firstred/postnl-api-php#17]
At this moment we create a shipment and get a PDF label:

```
        $labelFile = BP . self::LABELS_DIR . $this->barcode . '.pdf';
        $pdf = base64_decode($this->label->getResponseShipments()[0]->getLabels()[0]->getContent());
        file_put_contents($labelFile, $pdf);
        return $this;
```

However, this will result in a folder with a long list generated PDF's, so it does not look like a proper way to do this. Actually we're looking for a similar approach to the Sendcloud API where a label-URL can be requested through the API:
https://docs.sendcloud.sc/api/v2/shipping/#get-a-pdf-label

Is there any similar way to do this with the PostNL API?

**Comment by TomKriek** [comment]
You can just output the base64decoded label as a file to save for the user, instead of saving it to disk locally.

**Comment by zmip** [comment]
A simple solution would be to clean up the cached PDF label files with a cron job.

**Comment by GetMagented** [comment]
Thank you for your replies. We ended up using TomKriek's solution and output the label together with some additional information as 1 merged PDF using FPDF

**Comment by firstred** [comment]
I am going to double-check if the library properly supports this after merging the labels. It should be as easy as:

```php
<?php
$postnl = new PostNL(...);

header("Content-type:application/pdf");
header("Content-Disposition:attachment;filename=postnl-label-923323.pdf");
echo $postnl->getMergedLabels(); // Would prob. require some kind of __toString() implementation
exit;
```
