### ISSUE TITLE
Invalid API Response 

### ISSUE THREAD

**Issue by atif-majeed** [firstred/postnl-api-php#20]
I am using postnl labelling services. I am getting an error when I make the request for labelling.  here is my the Response Exception 
Fatal error: Uncaught ThirtyBees\PostNL\Exception\ResponseException: Invalid API Response in E:\wamp64\www\postnl-api-php\src\Service\BarcodeService.php on line 243

**Comment by firstred** [comment]
Thanks for raising this issue!

We're aware that, currently, not all services are working as they should. An effort is being made to release version 1.2.0, which should address this issue.
