### ISSUE TITLE
Uk shipments

### ISSUE THREAD

**Issue by CrossInternet** [firstred/postnl-api-php#25]
Creating a barcode for UK global package is not supported right now. 

UK is leaving the EU, so the packages need to be send as a global package. 

https://developer.postnl.nl/brexit/

Will this be fixed soon in the api?

**Comment by firstred** [comment]
Have you tried to remove GB from the 3S countries constant? Line https://github.com/firstred/postnl-api-php/blob/v1.2.x/src/PostNL.php#L115

Note that this is an unofficial library for the PostNL API, you should be able to make it work again by patching the library for the time being.

**Comment by firstred** [comment]
3S countries constant has been updated
