### ISSUE TITLE
GuzzleHttp dependency exception

### ISSUE THREAD

**Issue by rowhel95** [firstred/postnl-api-php#26]
When updating composer my Guzzle upgraded from 6 to 7 and guzzle uses new constant for version: MAJOR_VERSION

**Exception**
message: Undefined class constant 'VERSION' 
file: /vendor/firstred/postnl-api-php/src/PostNL.php
line: 383

below an example code from another package for whats needs to happen:

if (defined('\GuzzleHttp\ClientInterface::MAJOR_VERSION')) { // Guzzle 7
    $this->addVersionString("Guzzle/" . ClientInterface::MAJOR_VERSION);
} elseif (defined('\GuzzleHttp\ClientInterface::VERSION')) { // Before Guzzle 7
    $this->addVersionString("Guzzle/" . ClientInterface::VERSION);

**Comment by firstred** [comment]
Thanks for the information! It seems that the (breaking) changes in v7 Guzzle don't have an impact on the library. So I'll try your suggested changes.

Note that the `GuzzleClient` can be replaced with the `HttpPlugClient` from 1.2.0 on, which makes it possible to use more HTTP clients in the future. I'll update the documentation as soon as it is released.

**Comment by firstred** [comment]
Added this check to the client.
