### ISSUE TITLE
Blanc label for International Mail & Packets

### ISSUE THREAD

**Issue by Leondejoode** [firstred/postnl-api-php#27]
When I try to create a Label for Product 6350 the label is only showing a barcode.

This is happening with all products under International Mail & Packets (https://developer.postnl.nl/browse-apis/send-and-track/products/#destination-EU)

I would like to use 6350 to send packages from the Netherlands to Belgium.

If I create a label with product 4952 with the same Shipping address everything is working fine.

Edit: I think it has to do something with the barcode type.
For product 6350 I need a "LA" barcode.
I've tried to use the generateBarcode() function but it won't accept 'LA'.

Edit2: I've contacted postnl support because I was receiving unautorized messages when I did a manual CURL request for a LA barcode.
They have fixed that issue but unfortunately post-api-php can't handle LA barcodes.
Error: 
Fatal error: Uncaught ThirtyBees\PostNL\Exception\CifException: Validation failed for shipment: LAKTLxxxxxxxNL, Messages: LAKTLxxxxxxxNL: {[10303] Barcode is geen 3S}

Can someone please help?

**Comment by firstred** [comment]
Hi Leon,

Do you think that adding `LA` to the `generateBarcode` function would fix the whole issue? Have you tried patching this line https://github.com/firstred/postnl-api-php/blob/v1.2.x/src/PostNL.php#L885 and were you able to create a shipment label?

**Comment by firstred** [comment]
That's probably not going to solve it. On this page there's more information: https://developer.postnl.nl/browse-apis/send-and-track/barcode-webservice/documentation-soap/

**Comment by firstred** [comment]
Turns out the new shipment product has a whole new range. It's not the customer code nor is it the globalpack customer code. It seems to be hardcoded to just `NL`.

I'll update v1.2.0 to set the range to `NL` in case the shipment is one of: `LA`, `UE`, `RI`

**Comment by Leondejoode** [comment]
Hi firstred,

Thank you so much for your help!

**Comment by firstred** [comment]
I made a quick release to test the update: https://github.com/firstred/postnl-api-php/releases/tag/v1.2.0-alpha.1

If you're okay with lowering the [min stability requirement](https://getcomposer.org/doc/04-schema.md#minimum-stability) in `composer.json` then you're able to use the new release straight away.

**Comment by Leondejoode** [comment]
Thank you, I've just installed this version but first I need to fix this issue.
Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. 

I will post an update asap.

**Comment by firstred** [comment]
Thanks for the update!

I am trying to prevent the error you are seeing right now. I would like to allow for more HTTP clients with v1.2.0, but this error shouldn't occur, because the old Guzzle client is still supported. I'll see what I can do; you shouldn't have to install an additional client.

**Comment by firstred** [comment]
Ahh, now I see. It should catch the exception.
The PostNL library now prefers to check for all Http client alternatives that are available and falls back onto the embedded GuzzleClient or CurlClient when nothing else can be found.

An Async or Guzzle client is definitely preferred since these are the ones that can do concurrent requests and speed things up. Just like the previous version it is supposed to still work with Guzzle 6 (+ 7 now) directly, so I am going to add a fix for the Http client discovery problem.

**Comment by firstred** [comment]
I just created a new release which should solve the problems, but please be aware that the tests currently do not pass.

**Comment by Leon-d-j** [comment]
Yes it's working! I'm getting the label.
The only thing I had to change is: if (!in_array($type, ['2S', '3S','LA', 'UE', 'RI']) || 2 !== strlen($type)) {
On line 1027 because it will fail this check.

Thank you so much for your help!

**Comment by firstred** [comment]
Thanks, I have just pushed a new commit which just removes the `in_array` check altogether. With all the new types I think the `2 !== strlen($type)` would be sufficient for now.
